[tool.poetry]
name = "brokersystem"
version = "0.2.9"
description = "A Python module for communicating with brokersystem"
license = "ISC"
authors = ["chocolate <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31"
logzero = "^1.7"
pandas = "^2.0"
pillow = ">=10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
